### ISSUE TITLE
Note the Px to Pt scale of your PC screen

### ISSUE THREAD

**Issue by Robin-Rhee** [Kito0615/AppIconAutoMaker#1]
The scale factor from Px to Pt is 1 in antique Mac but 2 in retina screen of contemporary Mac.
We have to take it into account that the coordinate system is all about pt when we call -[NSImage drawInRect:](and some identical/similar methods).But it'll count on px dimensions with the app icons applied in our projects.
It's necessary to convert the size defined in SizeFile.plist to a px-consistent size like this
- (void)outputImage:(NSImage *)image InfoDict:(NSDictionary *)infoDict keysArr:(NSArray *)keysArr {
  //Reckon on a intermediate view to calculate the scale of current screen
  NSView *view = [NSView new];
  // Figure out the scale of pixels to points
  CGFloat scale = [view convertSizeToBacking:CGSizeMake(1,1)].width;
  
  for (NSString \* sizeKey in keysArr) {
      NSDictionary \* iconInfoDict = [infoDict objectForKey:sizeKey];
      NSString \* iconSizeString = [iconInfoDict objectForKey:@"Dimensions"];
      NSSize iconSize = NSSizeFromString(iconSizeString);
      NSString \* iconName = [iconInfoDict objectForKey:@"Name"];
      [self outputImage:image withSize:CGSizeMake(iconSize.width/scale, iconSize.height/scale) andName:iconName];
  }
  
  [[NSWorkspace sharedWorkspace] openURL:[NSURL URLWithString:[NSString stringWithFormat:@"file://%@", self.pathFiled.stringValue]]];
  }

**Comment by Kito0615** [comment]
Thanks. Fix this immediately.
