### ISSUE TITLE
增加通知的图标

### ISSUE THREAD

**Issue by bagyaru** [Kito0615/AppIconAutoMaker#2]
icon-notification@2x   and  icon-notification@3x

**Comment by Kito0615** [comment]
我不是很清楚你要增加什么？可以说详细一点吗？

**Comment by Kito0615** [comment]
我不是很清楚你要增加什么？可以说详细一点吗？

**Comment by Kito0615** [comment]
我不是很清楚你要增加什么？可以说详细一点吗？
